from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1082, 770)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(300, 110, 721, 321))
        self.graphicsView.setObjectName("graphicsView")
        self.lbl_Titulo = QtWidgets.QLabel(self.centralwidget)
        self.lbl_Titulo.setGeometry(QtCore.QRect(360, 10, 301, 91))
        font = QtGui.QFont()
        font.setFamily("Adobe Pi Std")
        font.setPointSize(28)
        self.lbl_Titulo.setFont(font)
        self.lbl_Titulo.setObjectName("lbl_Titulo")
        self.CombBox_Port = QtWidgets.QComboBox(self.centralwidget)
        self.CombBox_Port.setGeometry(QtCore.QRect(120, 190, 73, 22))
        self.CombBox_Port.setObjectName("CombBox_Port")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 190, 81, 16))
        self.label_2.setObjectName("label_2")
        self.lbl_BaudRate = QtWidgets.QLabel(self.centralwidget)
        self.lbl_BaudRate.setGeometry(QtCore.QRect(30, 250, 81, 16))
        self.lbl_BaudRate.setObjectName("lbl_BaudRate")
        self.TextEdit_BaudRate = QtWidgets.QTextEdit(self.centralwidget)
        self.TextEdit_BaudRate.setGeometry(QtCore.QRect(110, 240, 104, 31))
        self.TextEdit_BaudRate.setObjectName("TextEdit_BaudRate")
        self.btn_Puerto = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Puerto.setGeometry(QtCore.QRect(40, 300, 201, 28))
        self.btn_Puerto.setObjectName("btn_Puerto")
        self.btn_Start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Start.setGeometry(QtCore.QRect(40, 350, 201, 28))
        self.btn_Start.setObjectName("btn_Start")
        self.btn_Adquirir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Adquirir.setGeometry(QtCore.QRect(40, 400, 201, 28))
        self.btn_Adquirir.setObjectName("btn_Adquirir")
        self.btn_Detener = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Detener.setGeometry(QtCore.QRect(40, 450, 201, 28))
        self.btn_Detener.setObjectName("btn_Detener")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_Titulo.setText(_translate("MainWindow", "VDA - GUI"))
        self.label_2.setText(_translate("MainWindow", "Puerto COM"))
        self.lbl_BaudRate.setText(_translate("MainWindow", "BaudRate"))
        self.btn_Puerto.setText(_translate("MainWindow", "Abrir Puerto"))
        self.btn_Start.setText(_translate("MainWindow", "Start"))
        self.btn_Adquirir.setText(_translate("MainWindow", "Adquirir"))
        self.btn_Detener.setText(_translate("MainWindow", "Detener"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
